version: '3'

services:
  next:
    build: .
    ports: [3000:3000]
    environment:
      - PIAPI_KEY
      - KLING_PROVIDER=piapi
      - ADMIN_TOKEN
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next